server:
  port: 8080
  address: 0.0.0.0
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/mamacare_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: WajuDynamics1.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
  mail:
    host: smtp.zeptomail.com
    port: 587
    username: emailapikey
    password: wSsVR61zqRXxXf90nDf+crw+mFtdVlOiRE0s3VOnv3D5F/mU9sdqxkTJV1fzSvkbQDNrFGZG8r1/nxdTgWAKh44lmV5TDyiF9mqRe1U4J3x17qnvhDzNWW5UmxWJKogIxgtsn2lpE8Aq+g==
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2


# Keep your other settings below
application:
  security:
    oauth2:
      client:
        registration:
          google:
            # ----------------------------------------------------
            # 🔐 ADD YOUR GOOGLE CLIENT ID HERE LATER
            # ----------------------------------------------------
            client-id: "[REPLACE_WITH_YOUR_GOOGLE_CLIENT_ID]"
    jwt:
      secret-key: cnHInY4GRVqKLB1PetMHWdJcJpP0CBhZyBhA5giUByE=
      expiration: 86400000
      refresh-token:
        expiration: 604800000
cors:
  allowed-origins: "http://localhost:19006,http://localhost:8081,http://172.25.96.1:19006,http://172.25.96.1:8081,http://192.168.1.111:19006,http://192.168.1.111:8081,http://192.168.1.178:19006,http://192.168.1.178:8081,http://172.20.10.3:19006,http://172.20.10.3:8081,http://localhost:3000,http://localhost:3001"

community:
  copy:
    screen-title: "Community"
    hero-message: "You are not alone, Mama!"
    search-placeholder: "Search questions, topics or moms"
    ask-question-label: "Ask a Question"
    footer-title: "Be kind, be supportive, be you."
    footer-body: "This is safe space for every mama."
    tabs:
      - "Discussion"
      - "Groups"
      - "Events"

storage:
  type: local # Options: local, gcp
  local:
    upload-dir: uploads
  gcp:
    bucket-name: mamacare-audios
    credentials-path: 